#!/bin/bash -e

# install thumbsup
# unless it's already installed or symlinked
if [ ! -e "node_modules/thumbsup" ]; then
  npm install thumbsup
fi

# generate all samples galleries
# with different themes and settings
thumbsup --config source/default-folders.json
